export const strings = {
  auth: {
    login: '로그인',
    logout: '로그아웃',
    signup: '회원가입',
    email: '이메일',
    password: '비밀번호',
    loginButton: '로그인하기',
    signupButton: '회원가입하기',
    emailPlaceholder: '이메일 주소를 입력해주세요',
    passwordPlaceholder: '비밀번호를 입력해주세요',
    googleLogin: 'Google로 계속하기',
    appleLogin: 'Apple로 계속하기',
    kakaoLogin: '카카오로 계속하기',
    orDivider: '또는',
    noAccount: '계정이 없으신가요?',
    loginTitle: '로그인',
    loginSubtitle: '웅깅에 오신 것을 환영해요',
    forgotPassword: '비밀번호 찾기',
    emailRequired: '이메일과 비밀번호를 입력해주세요',
    registerTitle: '계정을 만들어요',
    registerSubtitle: '웅깅에 오신 것을 환영해요',
    name: '이름',
    namePlaceholder: '이름을 입력해주세요',
    passwordConfirm: '비밀번호 확인',
    passwordConfirmPlaceholder: '비밀번호를 한 번 더 입력해주세요',
    nextButton: '다음',
    registerButton: '가입하기',
    hasAccount: '이미 계정이 있으신가요?',
    nameRequired: '이름을 입력해주세요',
    emailInvalid: '올바른 이메일 형식을 입력해주세요',
    passwordTooShort: '비밀번호는 8자 이상이어야 해요',
    passwordMismatch: '비밀번호가 일치하지 않아요',
  },
  common: {
    confirm: '확인',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
    edit: '수정',
    back: '뒤로',
    loading: '로딩 중...',
    error: '오류가 발생했어요. 다시 시도해주세요.',
    networkError: '네트워크 연결을 확인해주세요.',
  },
  // 역할 표시명
  roles: {
    admin: '원장님',
    teacher: '선생님',
    student: '학생',
    parent: '학부모',
  },
  // 휴대폰 OTP 인증
  phoneVerify: {
    title: '휴대폰 인증',
    subtitle: '본인 확인을 위해 휴대폰 번호를 인증해주세요',
    phonePlaceholder: '휴대폰 번호 (예: 01012345678)',
    sendOtp: '인증번호 받기',
    resendOtp: '재전송',
    resendTimerSuffix: '초 후 재전송',
    otpTitle: '인증번호를 입력해주세요',
    otpSentPrefix: '',
    otpSentSuffix: '로 전송된 6자리 코드를 입력해주세요',
    confirm: '확인',
    phoneRequired: '휴대폰 번호를 입력해주세요',
    otpIncomplete: '인증번호 6자리를 모두 입력해주세요',
  },
  // 가입 온보딩 흐름
  onboarding: {
    selectRole: '역할을 선택해주세요',
    selectRoleDesc: '학원에서 맡은 역할을 선택해주세요',
    academyCode: '학원코드 입력',
    academyCodePlaceholder: '학원코드를 입력해주세요',
    inviteCode: '반 코드 입력',
    inviteCodePlaceholder: '반 코드를 입력해주세요',
    linkCode: '자녀 연동코드 입력',
    linkCodePlaceholder: '자녀의 연동코드를 입력해주세요',
    pending: '승인 대기 중',
    createAcademy: '학원 만들기',
    createAcademySubtitle: '학원 정보를 입력해주세요',
    academyName: '학원 이름',
    academyNamePlaceholder: '학원 이름을 입력해주세요',
    ownerName: '대표자 이름',
    ownerNamePlaceholder: '대표자 이름을 입력해주세요',
    ownerPhone: '대표자 연락처',
    ownerPhonePlaceholder: '연락처를 입력해주세요',
    address: '주소',
    addressPlaceholder: '학원 주소를 입력해주세요',
    academyTypeTitle: '운영 유형을 선택해주세요',
    createAcademyBtn: '학원 만들기',
    allFieldsRequired: '모든 항목을 입력해주세요',
    codeInputTitle: '코드를 입력해주세요',
    // 역할별 코드 입력 화면
    codeInput: {
      teacher: {
        title: '학원 코드 입력',
        subtitle: '원장님께 받은 6자리 코드를 입력해주세요',
        placeholder: '학원 코드를 입력해주세요',
        joinLabel: '이 학원에 참여하기',
        previewEmoji: '🏫',
      },
      student: {
        title: '반 코드 입력',
        subtitle: '선생님께 받은 6자리 코드를 입력해주세요',
        placeholder: '반 코드를 입력해주세요',
        joinLabel: '이 반에 참여하기',
        previewEmoji: '📚',
      },
      parent: {
        title: '연동 코드 입력',
        subtitle: '자녀에게 받은 6자리 코드를 입력해주세요',
        placeholder: '연동 코드를 입력해주세요',
        joinLabel: '이 코드로 연동하기',
        previewEmoji: '👶',
      },
    },
    confirm: '확인',
    lockedMessage: '잠시 후 다시 시도해주세요',
    lockedSuffix: '초 후 재시도',
    pendingTitle: '승인 대기 중이에요',
    pendingDesc: '관리자 승인 후 모든 기능을 이용할 수 있어요',
    pendingAllowedTitle: '지금 사용 가능한 기능',
    pendingBlockedTitle: '승인 후 사용 가능한 기능',
    pendingAllowed1: '학생 최대 3명 등록',
    pendingAllowed2: '반 1개 운영',
    pendingAllowed3: '기본 출결·숙제·공지',
    pendingBlocked1: '선생님 초대',
    pendingBlocked2: 'Pro 플랜 전환',
    // 역할별 설명
    adminDesc: '학원을 운영하고 관리해요',
    teacherDesc: '수업을 담당하고 학생을 관리해요',
    studentDesc: '숙제를 제출하고 출결을 확인해요',
    parentDesc: '자녀의 학습 현황을 확인해요',
  },
  // 숙제
  homework: {
    title: '숙제',
    submit: '제출',
    resubmit: '재제출',
    dueDate: '마감일',
    noHomework: '숙제가 없어요',
    submitted: '제출 완료',
    checked: '검사 완료',
    late: '지각 제출',
    feedback: '피드백',
    pass: '통과',
    retry: '다시 해오기',
    maxImages: '최대 5장까지 첨부할 수 있어요',
    scanGuide: '숙제를 카메라로 촬영해주세요',
  },
  // 출결
  attendance: {
    title: '출결',
    myTitle: '내 출결',
    present: '출석',
    late: '지각',
    absent: '결석',
    onLeave: '휴원',
    reason: '결석 사유',
    reasonPlaceholder: '결석 사유를 입력해주세요',
    lateReasonPlaceholder: '지각 사유를 입력해주세요',
    submitReason: '사유 전송',
    absenceReasons: ['🏥 병원', '👨‍👩‍👧 가족행사', '✏️ 기타'],
    rosterTable: '출석',
    exportExcel: '엑셀 내보내기',
    noClassMessage: '반에 참여한 후 확인할 수 있어요',
    noClassSub: '선생님께 반 초대 코드를 받아 참여해주세요',
    loadFailed: '출결 정보를 불러오지 못했어요',
    noReason: '사유가 입력되지 않았어요',
    summaryTitle: '이번달 요약',
    days: (n: number) => `${n}일`,
    // 출결 상태 레이블 (그룹 객체 — 동적 키 접근용)
    statusLabels: {
      present: '출석',
      late: '지각',
      absent: '결석',
      onLeave: '휴원',
    },
    // 출결 저장 실패 오류 메시지
    errorSaveFailed: '출결 저장에 실패했어요. 다시 시도해주세요.',
    // 결석 사유 전송 성공
    reasonSentSuccess: '결석 사유가 선생님께 전달됐어요.',
    // 출결 데이터 없음 안내
    noData: '출결 기록이 없어요.',
    // 반 선택 안내 (admin 출결 화면)
    selectClass: '반을 선택하세요',
    // 월간 캘린더 전용
    calendar: {
      dayHeaders: ['월', '화', '수', '목', '금', '토', '일'],
      legendPresent: '출석',
      legendLate: '지각',
      legendAbsent: '결석',
      yearMonth: (year: number, month: number) => `${year}년 ${month}월`,
    },
  },
  // 공지사항
  notice: {
    title: '공지사항',
    important: '중요',
    noNotice: '공지가 없어요',
    write: '공지 작성',
    readCount: '명이 읽었어요',
    // 공지 작성 화면
    createTitle: '공지 작성',
    titlePlaceholder: '제목을 입력해주세요',
    contentPlaceholder: '내용을 입력해주세요',
    importantToggle: '중요 공지로 설정',
    saveButton: '공지 올리기',
    deleteConfirm: '이 공지를 삭제할까요?',
    noContent: '내용이 없어요',
    // 읽음 현황
    readStatus: '읽음 현황',
    proFeatureName: '공지 읽음 현황',
    readUsers: '읽은 사람',
    unreadUsers: '아직 안 읽은 사람',
    noReaders: '아직 아무도 읽지 않았어요',
    // 공지 대상 선택
    targetLabel: '공지 대상 반',
    targetAll: '전체 반',
    targetSelect: '반 선택',
    targetNoneSelected: '반을 선택해주세요',
    targetClassCount: (n: number) => `${n}개 반 선택됨`,
    // 수신 역할 선택
    targetRoleLabel: '수신 대상',
    targetRoleAll: '모두',
    targetRoleStudentOnly: '학생만',
    targetRoleParentOnly: '학부모만',
  },
  // 알림 인박스
  notification: {
    inbox: '알림',
    empty: '알림이 없어요',
    markAllRead: '모두 읽음',
  },
  // 학부모 전용 문자열
  parent: {
    childHomework: '자녀 숙제',
    noHomework: '숙제가 없어요',
    switchChild: '자녀 전환',
    childAttendance: '자녀 출결',
    notSubmitted: '미제출',
    submitted: '검사 대기',
    done: '완료',
    feedbackPass: '잘했어요',
    feedbackRetry: '다시 해오기',
    noChildren: '연동된 자녀가 없어요',
    childDetail: '자녀 숙제 상세',
  },
  // 내정보 (학부모 프로필)
  profile: {
    title: '내 정보',
    linkedChildren: '연동된 자녀',
    addChild: '+ 자녀 추가 연동',
    unlink: '연동해제',
    unlinkConfirmTitle: '연동을 해제할까요?',
    unlinkConfirmDesc: (name: string) => `${name} 자녀와의 연동이 해제됩니다.`,
    homeworkNotif: '숙제 알림',
    noticeNotif: '공지 알림',
    inquiry: '문의하기',
    inquiryEmail: 'support@woongking.kr',
    noClass: '반 미정',
    unlinkFailed: '연동 해제에 실패했어요.',
    childrenCount: (n: number) => `학부모 · 자녀 ${n}명 연동`,
    noChildren: '연동된 자녀가 없어요',
  },
  // 엑셀 내보내기 (Phase 6)
  // 주의: strings.attendance.exportExcel 키와 중복되지 않도록 여기서는 별도 그룹으로 관리
  export: {
    // ── UI 문자열 ──────────────────────────────────
    title: '출결 내보내기',
    selectClass: '반을 선택해주세요',
    selectMonth: '월을 선택해주세요',
    exportButton: '엑셀 파일 내보내기',
    generating: '파일 생성 중...',
    shareError: '파일 생성에 실패했어요. 다시 시도해주세요',
    noStudents: '이 반에 학생이 없어요',
    proFeatureName: '출결 엑셀 내보내기',

    // ── 엑셀 파일 내부 컬럼 헤더 ──────────────────
    colNumber: '번호',
    colName: '성명',
    colBirthDate: '생년월일',
    colGuardianPhone: '보호자연락처',
    colSubjectClass: '교습과목 및 수강반',
    colEnrollPeriod: '수강기간',
    colPresentTotal: '출석합계',
    colLateTotal: '지각합계',
    colAbsentTotal: '결석합계',
    colAttendRate: '출석률',
  },
  // 오류 메시지
  errors: {
    codeNotFound: '코드를 찾을 수 없어요',
    duplicatePhone: '이미 가입된 번호예요. 로그인해주세요',
    tooManyAttempts: '잠시 후 다시 시도해주세요',
    invalidCode: '올바르지 않은 코드예요',
    uploadFailed: '업로드에 실패했어요. 다시 시도해주세요',
    permissionDenied: '권한이 없어요',
  },
};
