export const strings = {
  auth: {
    login: '로그인',
    logout: '로그아웃',
    signup: '회원가입',
    email: '이메일',
    password: '비밀번호',
    loginButton: '로그인하기',
    signupButton: '회원가입하기',
  },
  common: {
    confirm: '확인',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
    edit: '수정',
    back: '뒤로',
    loading: '로딩 중...',
    error: '오류가 발생했어요. 다시 시도해주세요.',
    networkError: '네트워크 연결을 확인해주세요.',
  },
  // 역할 표시명
  roles: {
    admin: '원장님',
    teacher: '선생님',
    student: '학생',
    parent: '학부모',
  },
  // 가입 온보딩 흐름
  onboarding: {
    selectRole: '역할을 선택해주세요',
    selectRoleDesc: '학원에서 맡은 역할을 선택해주세요',
    academyCode: '학원코드 입력',
    academyCodePlaceholder: '학원코드를 입력해주세요',
    inviteCode: '반 코드 입력',
    inviteCodePlaceholder: '반 코드를 입력해주세요',
    linkCode: '자녀 연동코드 입력',
    linkCodePlaceholder: '자녀의 연동코드를 입력해주세요',
    pending: '승인 대기 중',
    pendingDesc: '학원 승인 후 모든 기능을 이용할 수 있어요',
    createAcademy: '학원 만들기',
    academyName: '학원 이름',
    ownerName: '대표자 이름',
    ownerPhone: '대표자 연락처',
    address: '주소',
  },
  // 숙제
  homework: {
    title: '숙제',
    submit: '제출',
    resubmit: '재제출',
    dueDate: '마감일',
    noHomework: '숙제가 없어요',
    submitted: '제출 완료',
    checked: '검사 완료',
    late: '지각 제출',
    feedback: '피드백',
    pass: '통과',
    retry: '다시 해오기',
    maxImages: '최대 5장까지 첨부할 수 있어요',
    scanGuide: '숙제를 카메라로 촬영해주세요',
  },
  // 출결
  attendance: {
    title: '출결',
    present: '출석',
    late: '지각',
    absent: '결석',
    onLeave: '휴원',
    reason: '결석 사유',
    reasonPlaceholder: '결석 사유를 입력해주세요',
    submitReason: '사유 전송',
    rosterTable: '명렬표',
    exportExcel: '엑셀 내보내기',
  },
  // 공지사항
  notice: {
    title: '공지사항',
    important: '중요',
    noNotice: '공지가 없어요',
    write: '공지 작성',
    readCount: '명이 읽었어요',
  },
  // 오류 메시지
  errors: {
    codeNotFound: '코드를 찾을 수 없어요',
    duplicatePhone: '이미 가입된 번호예요. 로그인해주세요',
    tooManyAttempts: '잠시 후 다시 시도해주세요',
    invalidCode: '올바르지 않은 코드예요',
    uploadFailed: '업로드에 실패했어요. 다시 시도해주세요',
    permissionDenied: '권한이 없어요',
  },
};
