export const strings = {
  auth: {
    login: '로그인',
    logout: '로그아웃',
    signup: '회원가입',
    email: '이메일',
    password: '비밀번호',
    loginButton: '로그인하기',
    signupButton: '회원가입하기',
    emailPlaceholder: '이메일 주소를 입력해주세요',
    passwordPlaceholder: '비밀번호를 입력해주세요',
    googleLogin: 'Google로 계속하기',
    appleLogin: 'Apple로 계속하기',
    kakaoLogin: '카카오로 계속하기',
    orDivider: '또는',
    noAccount: '계정이 없으신가요?',
    loginTitle: '다시 만나서 반가워요',
    loginSubtitle: 'EduOnePass에 로그인하세요',
    emailRequired: '이메일과 비밀번호를 입력해주세요',
    registerTitle: '계정을 만들어요',
    registerSubtitle: 'EduOnePass에 오신 것을 환영해요',
    name: '이름',
    namePlaceholder: '이름을 입력해주세요',
    passwordConfirm: '비밀번호 확인',
    passwordConfirmPlaceholder: '비밀번호를 한 번 더 입력해주세요',
    nextButton: '다음',
    hasAccount: '이미 계정이 있으신가요?',
    nameRequired: '이름을 입력해주세요',
    emailInvalid: '올바른 이메일 형식을 입력해주세요',
    passwordTooShort: '비밀번호는 8자 이상이어야 해요',
    passwordMismatch: '비밀번호가 일치하지 않아요',
  },
  common: {
    confirm: '확인',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
    edit: '수정',
    back: '뒤로',
    loading: '로딩 중...',
    error: '오류가 발생했어요. 다시 시도해주세요.',
    networkError: '네트워크 연결을 확인해주세요.',
  },
  // 역할 표시명
  roles: {
    admin: '원장님',
    teacher: '선생님',
    student: '학생',
    parent: '학부모',
  },
  // 휴대폰 OTP 인증
  phoneVerify: {
    title: '휴대폰 인증',
    subtitle: '본인 확인을 위해 휴대폰 번호를 인증해주세요',
    phonePlaceholder: '휴대폰 번호 (예: 01012345678)',
    sendOtp: '인증번호 받기',
    resendOtp: '재전송',
    resendTimerSuffix: '초 후 재전송',
    otpTitle: '인증번호를 입력해주세요',
    otpSentPrefix: '',
    otpSentSuffix: '로 전송된 6자리 코드를 입력해주세요',
    confirm: '확인',
    phoneRequired: '휴대폰 번호를 입력해주세요',
    otpIncomplete: '인증번호 6자리를 모두 입력해주세요',
  },
  // 가입 온보딩 흐름
  onboarding: {
    selectRole: '역할을 선택해주세요',
    selectRoleDesc: '학원에서 맡은 역할을 선택해주세요',
    academyCode: '학원코드 입력',
    academyCodePlaceholder: '학원코드를 입력해주세요',
    inviteCode: '반 코드 입력',
    inviteCodePlaceholder: '반 코드를 입력해주세요',
    linkCode: '자녀 연동코드 입력',
    linkCodePlaceholder: '자녀의 연동코드를 입력해주세요',
    pending: '승인 대기 중',
    createAcademy: '학원 만들기',
    createAcademySubtitle: '학원 정보를 입력해주세요',
    academyName: '학원 이름',
    academyNamePlaceholder: '학원 이름을 입력해주세요',
    ownerName: '대표자 이름',
    ownerNamePlaceholder: '대표자 이름을 입력해주세요',
    ownerPhone: '대표자 연락처',
    ownerPhonePlaceholder: '연락처를 입력해주세요',
    address: '주소',
    addressPlaceholder: '학원 주소를 입력해주세요',
    academyTypeTitle: '운영 유형을 선택해주세요',
    createAcademyBtn: '학원 만들기',
    allFieldsRequired: '모든 항목을 입력해주세요',
    codeInputTitle: '코드를 입력해주세요',
    confirm: '확인',
    lockedMessage: '잠시 후 다시 시도해주세요',
    lockedSuffix: '초 후 재시도',
    pendingTitle: '승인 대기 중이에요',
    pendingDesc: '관리자 승인 후 모든 기능을 이용할 수 있어요',
    pendingAllowedTitle: '지금 사용 가능한 기능',
    pendingBlockedTitle: '승인 후 사용 가능한 기능',
    pendingAllowed1: '학생 최대 3명 등록',
    pendingAllowed2: '반 1개 운영',
    pendingAllowed3: '기본 출결·숙제·공지',
    pendingBlocked1: '선생님 초대',
    pendingBlocked2: 'Pro 플랜 전환',
    // 역할별 설명
    adminDesc: '학원을 운영하고 관리해요',
    teacherDesc: '수업을 담당하고 학생을 관리해요',
    studentDesc: '숙제를 제출하고 출결을 확인해요',
    parentDesc: '자녀의 학습 현황을 확인해요',
  },
  // 숙제
  homework: {
    title: '숙제',
    submit: '제출',
    resubmit: '재제출',
    dueDate: '마감일',
    noHomework: '숙제가 없어요',
    submitted: '제출 완료',
    checked: '검사 완료',
    late: '지각 제출',
    feedback: '피드백',
    pass: '통과',
    retry: '다시 해오기',
    maxImages: '최대 5장까지 첨부할 수 있어요',
    scanGuide: '숙제를 카메라로 촬영해주세요',
  },
  // 출결
  attendance: {
    title: '출결',
    present: '출석',
    late: '지각',
    absent: '결석',
    onLeave: '휴원',
    reason: '결석 사유',
    reasonPlaceholder: '결석 사유를 입력해주세요',
    submitReason: '사유 전송',
    rosterTable: '명렬표',
    exportExcel: '엑셀 내보내기',
  },
  // 공지사항
  notice: {
    title: '공지사항',
    important: '중요',
    noNotice: '공지가 없어요',
    write: '공지 작성',
    readCount: '명이 읽었어요',
  },
  // 오류 메시지
  errors: {
    codeNotFound: '코드를 찾을 수 없어요',
    duplicatePhone: '이미 가입된 번호예요. 로그인해주세요',
    tooManyAttempts: '잠시 후 다시 시도해주세요',
    invalidCode: '올바르지 않은 코드예요',
    uploadFailed: '업로드에 실패했어요. 다시 시도해주세요',
    permissionDenied: '권한이 없어요',
  },
};
