// 웹 대시보드 UI 텍스트 상수
// 모든 UI 문자열은 여기서 import — 컴포넌트 내 하드코딩 금지

export const strings = {
  app: {
    name: '웅깅',
    dashboardTitle: '관리자 대시보드',
    subtitle: '웅깅 학원 관리 시스템',
  },
  auth: {
    login: '로그인',
    logout: '로그아웃',
    loginTitle: '원장님, 안녕하세요',
    loginSubtitle: '웅깅 관리자 대시보드에 로그인하세요',
    email: '이메일',
    emailPlaceholder: '이메일 주소를 입력해주세요',
    password: '비밀번호',
    passwordPlaceholder: '비밀번호를 입력해주세요',
    loginButton: '로그인',
    googleLogin: 'Google로 로그인',
    kakaoLogin: '카카오로 로그인',
    adminOnly: '원장님 계정으로만 접근할 수 있어요',
    notAdmin: '관리자 계정이 아니에요. 원장님 계정으로 로그인해주세요.',
    loginError: '로그인에 실패했어요. 이메일과 비밀번호를 확인해주세요.',
  },
  nav: {
    dashboard: '홈',
    students: '학생 관리',
    attendance: '출결 관리',
    teachers: '선생님 관리',
    notices: '공지사항',
    subscription: '구독/결제',
  },
  common: {
    confirm: '확인',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
    edit: '수정',
    add: '추가',
    search: '검색',
    filter: '필터',
    all: '전체',
    loading: '불러오는 중...',
    error: '오류가 발생했어요. 다시 시도해주세요.',
    noData: '데이터가 없어요',
    success: '완료되었어요',
    close: '닫기',
    download: '다운로드',
    upload: '업로드',
    copy: '복사',
    copied: '복사됨',
  },
  dashboard: {
    title: '오늘의 현황',
    present: '출석',
    late: '지각',
    absent: '결석',
    noRecord: '미입력',
    absentList: '오늘 결석 학생',
    noRecordList: '출결 미입력 학생',
    attendanceByClass: '반별 이번달 출석률',
    recentTrend: '최근 7일 출결 추이',
    subscriptionStatus: '구독 현황',
  },
  students: {
    title: '학생 관리',
    addStudent: '학생 추가',
    excelUpload: '엑셀 일괄 등록',
    name: '이름',
    class: '반',
    birthDate: '생년월일',
    guardianPhone: '보호자 연락처',
    enrollmentDate: '수강 시작일',
    status: '상태',
    active: '재원',
    inactive: '퇴원',
    deactivate: '퇴원 처리',
    deactivateConfirm: '정말 퇴원 처리할까요? 이 학생은 앱에 접근할 수 없게 돼요.',
    moveClass: '반 이동',
    noStudents: '등록된 학생이 없어요',
  },
  classes: {
    title: '반 관리',
    addClass: '반 추가',
    className: '반 이름',
    subject: '교습과목',
    inviteCode: '초대코드',
    studentCount: '학생 수',
    editClass: '반 수정',
    deleteClass: '반 삭제',
    deleteConfirm: '정말 이 반을 삭제할까요?',
    deleteWithStudentsWarning: '이 반에 소속된 학생이 있어요. 먼저 학생을 다른 반으로 이동해주세요.',
    noClasses: '등록된 반이 없어요',
  },
  attendance: {
    title: '출결 관리',
    date: '날짜',
    class: '반',
    student: '학생',
    status: '출결 상태',
    reason: '결석 사유',
    excelDownload: '엑셀 다운로드',
    reasonList: '결석 사유 목록',
    noReasons: '결석 사유가 없어요',
    selectMonth: '월 선택',
    selectClass: '반 선택',
  },
  teachers: {
    title: '선생님 관리',
    academyCode: '학원코드',
    copyCode: '코드 복사',
    assignedClasses: '담당 반',
    deleteTeacher: '계정 삭제',
    deleteConfirm: '정말 이 선생님 계정을 삭제할까요?',
    noTeachers: '등록된 선생님이 없어요',
  },
  notices: {
    title: '공지사항',
    addNotice: '공지 작성',
    noticeTitle: '제목',
    noticeContent: '내용',
    important: '중요 공지',
    readCount: '읽음',
    unreadList: '미읽음 목록',
    deleteConfirm: '정말 이 공지를 삭제할까요?',
    noNotices: '등록된 공지가 없어요',
  },
  subscription: {
    title: '구독/결제',
    currentPlan: '현재 플랜',
    free: '무료',
    trial: '체험판',
    pro: '프로',
    studentCount: '학생 수',
    expiresAt: '만료일',
    upgrade: '업그레이드',
    paymentHistory: '결제 내역',
    noPayments: '결제 내역이 없어요',
  },
};
