// 웹 대시보드 UI 텍스트 상수
// 모든 UI 문자열은 여기서 import — 컴포넌트 내 하드코딩 금지

export const strings = {
  app: {
    name: '웅깅',
    dashboardTitle: '관리자 대시보드',
    subtitle: '웅깅 학원 관리 시스템',
  },
  auth: {
    login: '로그인',
    logout: '로그아웃',
    loginTitle: '원장님, 안녕하세요',
    loginSubtitle: '웅깅 관리자 대시보드에 로그인하세요',
    email: '이메일',
    emailPlaceholder: '이메일 주소를 입력해주세요',
    password: '비밀번호',
    passwordPlaceholder: '비밀번호를 입력해주세요',
    loginButton: '로그인',
    googleLogin: 'Google로 로그인',
    kakaoLogin: '카카오로 로그인',
    adminOnly: '원장님 계정으로만 접근할 수 있어요',
    notAdmin: '관리자 계정이 아니에요. 원장님 계정으로 로그인해주세요.',
    loginError: '로그인에 실패했어요. 이메일과 비밀번호를 확인해주세요.',
  },
  nav: {
    dashboard: '홈',
    students: '학생 관리',
    attendance: '출결 관리',
    homework: '숙제 관리',
    teachers: '선생님 관리',
    notices: '공지사항',
    videos: '학습 영상',
    subscription: '구독/결제',
    settings: '학원 설정',
  },
  common: {
    confirm: '확인',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
    edit: '수정',
    add: '추가',
    search: '검색',
    filter: '필터',
    all: '전체',
    loading: '불러오는 중...',
    error: '오류가 발생했어요. 다시 시도해주세요.',
    noData: '데이터가 없어요',
    success: '완료되었어요',
    close: '닫기',
    download: '다운로드',
    upload: '업로드',
    copy: '복사',
    copied: '복사됨',
  },
  dashboard: {
    title: '오늘의 현황',
    present: '출석',
    late: '지각',
    absent: '결석',
    noRecord: '미입력',
    absentList: '오늘 결석 학생',
    noRecordList: '출결 미입력 학생',
    attendanceByClass: '반별 이번달 출석률',
    recentTrend: '최근 7일 출결 추이',
    subscriptionStatus: '구독 현황',
  },
  students: {
    title: '학생 관리',
    addStudent: '학생 추가',
    excelUpload: '엑셀 일괄 등록',
    name: '이름',
    class: '반',
    birthDate: '생년월일',
    guardianPhone: '보호자 연락처',
    enrollmentDate: '수강 시작일',
    status: '상태',
    active: '재원',
    inactive: '퇴원',
    deactivate: '퇴원 처리',
    deactivateConfirm: '정말 퇴원 처리할까요? 이 학생은 앱에 접근할 수 없게 돼요.',
    moveClass: '반 이동',
    noStudents: '등록된 학생이 없어요',
  },
  classes: {
    title: '반 관리',
    addClass: '반 추가',
    className: '반 이름',
    subject: '교습과목',
    inviteCode: '초대코드',
    studentCount: '학생 수',
    editClass: '반 수정',
    deleteClass: '반 삭제',
    deleteConfirm: '정말 이 반을 삭제할까요?',
    deleteWithStudentsWarning: '이 반에 소속된 학생이 있어요. 먼저 학생을 다른 반으로 이동해주세요.',
    noClasses: '등록된 반이 없어요',
  },
  attendance: {
    title: '출결 관리',
    date: '날짜',
    class: '반',
    student: '학생',
    status: '출결 상태',
    reason: '결석 사유',
    excelDownload: '엑셀 다운로드',
    reasonList: '결석 사유 목록',
    noReasons: '결석 사유가 없어요',
    selectMonth: '월 선택',
    selectClass: '반 선택',
    // 월별 출결 명렬표 페이지
    rosterTitle: '월별 출결 명렬표',
    rosterSubtitle: '출결을 입력한 날짜만 표시 · 화면 그대로 엑셀로 저장하세요',
    rosterEmpty: '선택한 반에 등록된 학생이 없어요',
    rosterSelectClass: '반을 선택해주세요',
    rosterBackToAttendance: '← 출결 관리로',
    rosterDownloadExcel: '이 화면을 엑셀로 저장',
    rosterLegend: '○ 출석 · △ 지각 · X 결석 · 빈 칸 미입력',
    rosterColPresent: '출석',
    rosterColLate: '지각',
    rosterColAbsent: '결석',
    rosterColRate: '출석률',
    rosterColTotal: '총 수업일',
  },
  teachers: {
    title: '선생님 관리',
    academyCode: '학원코드',
    copyCode: '코드 복사',
    assignedClasses: '담당 반',
    deleteTeacher: '계정 삭제',
    deleteConfirm: '정말 이 선생님 계정을 삭제할까요?',
    noTeachers: '등록된 선생님이 없어요',
    assignClasses: '반 배정',
    assignClassesTitle: '담당 반 배정',
    assignClassesDesc: '이 선생님이 담당할 반을 선택하세요. 학생 출결·숙제 권한이 자동 부여됩니다.',
    noClassesYet: '학원에 등록된 반이 없어요',
    saveAssignment: '저장',
  },
  notices: {
    title: '공지사항',
    addNotice: '공지 작성',
    noticeTitle: '제목',
    noticeContent: '내용',
    important: '중요 공지',
    readCount: '읽음',
    unreadList: '미읽음 목록',
    deleteConfirm: '정말 이 공지를 삭제할까요?',
    noNotices: '등록된 공지가 없어요',
    // 읽음 확인 — Pro 플랜 게이트 (standard/pro/trial 전용 기능)
    readConfirmLockedTitle: '읽음 확인은 스탠다드 플랜부터 이용할 수 있어요',
    readConfirmLockedDesc: '누가 공지를 확인했는지, 미확인자에게 재알림을 발송할 수 있어요.',
    readConfirmUpgrade: '플랜 업그레이드',
    readConfirmLockedShort: '🔒 읽음 확인 잠김',
  },
  // 승인 대기 / 반려 / 비활성 상태 안내 페이지
  approval: {
    pendingTitle: '학원 승인 대기 중이에요',
    pendingDesc: '심사가 끝나면 모든 기능이 활성화돼요. 보통 영업일 1~2일 안에 결과를 알려드려요.',
    pendingHelp: '심사가 너무 오래 걸리거나 궁금한 점이 있으면 카카오톡 채널로 문의해 주세요.',
    rejectedTitle: '승인이 반려되었어요',
    rejectedDesc: '아래 사유를 확인하시고 카카오톡 채널로 문의해 주시면 재신청을 도와드려요.',
    deactivatedTitle: '비활성 상태인 학원이에요',
    deactivatedDesc: '30일 이상 미승인 또는 관리자가 비활성화한 학원이에요. 재활성화는 카카오톡 채널로 문의해 주세요.',
    // 웹 대시보드는 Pro 플랜 전용 — 다른 플랜·만료 학원이 접근 시 안내
    proRequiredTitle: '웹 대시보드는 프로 플랜 전용이에요',
    proRequiredDesc: '학생 무제한·엑셀 일괄 업로드 등 웹 대시보드 기능을 이용하려면 프로 플랜으로 업그레이드해 주세요.',
    proRequiredHelp: '플랜 업그레이드는 앱의 학원 설정 화면에서 진행할 수 있어요. 결제 후 다시 로그인해 주세요.',
    submittedAt: '신청일',
    rejectReason: '반려 사유',
    contactKakao: '카카오톡 채널 문의',
    refresh: '새로고침',
    accountInfo: '계정 정보',
    academyName: '학원명',
    ownerName: '원장 성함',
    ownerPhone: '연락처',
    address: '주소',
    goToLogin: '다른 계정으로 로그인',
  },
  settings: {
    title: '학원 설정',
    academyInfo: '학원 정보',
    academyName: '학원명',
    academyType: '학원 유형',
    address: '주소',
    ownerInfo: '원장 정보',
    ownerName: '원장 성함',
    ownerPhone: '연락처',
    academyCode: '학원코드',
    academyCodeHelp: '선생님 가입 시 입력하는 코드예요. 신규 선생님께 공유하세요.',
    accountMeta: '계정 정보',
    submittedAt: '신청일',
    approvedAt: '승인일',
    statusPending: '승인 대기 중',
    statusPendingDesc: '심사가 끝나면 모든 기능이 활성화돼요. 보통 영업일 1~2일 소요돼요.',
    statusRejected: '승인 반려',
    statusActive: '정상 운영 중',
    saveSuccess: '저장됐어요',
    saveError: '저장에 실패했어요. 다시 시도해주세요.',
    pendingEditDisabled: '승인 후에 정보를 수정할 수 있어요',
    placeholderName: '예) 웅깅수학학원',
    placeholderOwnerName: '예) 김선생',
    placeholderPhone: '예) 010-1234-5678',
    placeholderAddress: '예) 서울시 강남구 테헤란로 123',
  },
  videos: {
    title: '학습 영상 관리',
    subtitle: 'YouTube 영상을 반별로 등록해서 학생 앱에 노출하세요',
    addVideo: '영상 등록',
    editVideo: '영상 수정',
    deleteVideo: '영상 삭제',
    deleteConfirm: '이 영상을 삭제할까요? 학생들도 더 이상 볼 수 없어요.',
    youtubeUrl: 'YouTube URL',
    youtubeUrlPlaceholder: 'https://youtu.be/...',
    videoTitle: '영상 제목',
    videoTitlePlaceholder: '영상 제목을 입력해주세요',
    targetClass: '대상 반',
    selectClass: '반을 선택해주세요',
    urlValid: '✓ 올바른 YouTube URL이에요',
    urlInvalid: '올바른 YouTube URL을 입력해주세요',
    noVideos: '등록된 영상이 없어요',
    noVideosDesc: '첫 영상을 등록하면 학생 앱에 즉시 노출돼요',
    noClasses: '먼저 반을 만들어 주세요',
    filterAll: '전체 반',
    classLabel: '반',
    openOnYoutube: 'YouTube에서 보기',
    saveError: '저장에 실패했어요. 다시 시도해주세요.',
    deleteError: '삭제에 실패했어요. 다시 시도해주세요.',
    // Pro 플랜 게이트 (starter 이상 — 즉 plan !== 'free')
    lockedTitle: '학습 영상은 유료 플랜부터 이용할 수 있어요',
    lockedDesc: 'YouTube 영상을 반별로 등록해서 학생 앱에서 바로 볼 수 있게 해보세요.',
    lockedUpgrade: '플랜 업그레이드',
  },
  subscription: {
    title: '구독/결제',
    currentPlan: '현재 플랜',
    free: '무료',
    trial: '체험판',
    pro: '프로',
    studentCount: '학생 수',
    expiresAt: '만료일',
    upgrade: '업그레이드',
    paymentHistory: '결제 내역',
    noPayments: '결제 내역이 없어요',
  },
};
